#!/bin/bash

COMMANDS="gcc -g -Wall -Werror -Wextra -pedantic *.c";
ACTIONS=("test" "vagrind" "gdb" "diff");
DIRECTORY_BUILD="build";
DIRECTORY_TEST="tests";
ARGUMENTS=("$@")
NO_HASH_TO_ACTION=1;

test()
{
	local SUFFIX="$1";
	$(echo sudo "$COMMANDS" ./tests/main-"$SUFFIX".c -o ./build/main-"$SUFFIX");
	$(echo sudo ./build/main-"$SUFFIX");
}

vagrind()
{
	local SUFFIX="$1";
	$(echo sudo "$COMMANDS" ./tests/main-"$SUFFIX".c -o ./build/main-"$SUFFIX");
	$(echo vagrind ./build/main-"$SUFFIX");
}

gdb()
{
	local SUFFIX="$1";
	$(echo sudo "$COMMANDS" ./tests/main-"$SUFFIX".c -o ./build/main-"$SUFFIX");
	$(echo gdb ./build/main-"$SUFFIX");
}
err()
{
	echo "$*" >>/dev/stderr;
}



for ACTION in "${ACTIONS[@]}"; do
	if [[ $# -le 1 ]]; then
		err "Parameters is less than or equal to int 1";
		break;
	else
		if [ "${ARGUMENTS[0]}" = "$ACTION" ]; then
			NO_HASH_TO_ACTION=0;
			"$ACTION" "${ARGUMENTS[@]:1}";
		fi
	fi
done
if [[ $NO_HASH_TO_ACTION -eq 1 ]]; then
	err "tu atrubito \"${ARGUMENTS[0]}\" no es valido";
fi


